title:              GeraSoft.com - Get All Amazon Competition Details Updated Daily
email:              admin@gerasoft.com
author:             Vignesh
baseurl:            "/startbootstrap-clean-blog-jekyll/"
url:                "http://www.gerasoft.com/"


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
  - jekyll-toc
